-- NOTE that sqlalchemy/database.sql is a symbolic link to sql/database.sql. ALL changes will be reflected in the sqlalchemy assessment.

CREATE TABLE users (
    user_id VARCHAR(5) PRIMARY KEY,
    email VARCHAR(50) NOT NULL,
    password VARCHAR(50),
    user_name VARCHAR(50),
    user_type VARCHAR(50)
);

CREATE TABLE templates (
    template_id SERIAL PRIMARY KEY,
    template_name VARCHAR(50) NOT NULL,
    user_id VARCHAR(5),
    updated_at DATE
);

-- Create an Awards Table

CREATE TABLE template_questions (
                     template_name VARCHAR NOT NULL,
                     template_question_id SERIAL PRIMARY KEY,
                     question VARCHAR NOT NULL,
                     yes_text VARCHAR NOT NULL,
                     no_text VARCHAR NOT NULL,
                     not_applicable_text VARCHAR NOT NULL,
                     help_text VARCHAR NOT NULL,
                     resource_url VARCHAR NOT NULL,
                     category VARCHAR NOT NULL,
                     primary_driver BOOLEAN NOT NULL,
                     preparer_answer VARCHAR,
                     preparer_time_spent INTEGER,
                     preparer_comment VARCHAR,
                     reviewer_full_name VARCHAR,
                     reviewer_email VARCHAR,
                     reviewer_id INTEGER,
                     date_sent_to_review DATE,
                     reviewer_comment VARCHAR,
                     reviewer_answer VARCHAR,
                     reviewer_time_spent INTEGER,
                     date_review_completed DATE,
                     recipient_full_name VARCHAR,
                     recipient_email VARCHAR,
                     date_sent_to_recipient DATE
                     );

-- Insert Users
INSERT INTO users (user_id, email, password, user_name, user_type) VALUES
(1, 'annewoosamcode@gmail.com', 'testac','Anne Woo-Sam','creator'),
(2, 'retiringwiser@gmail.com', 'testrw', 'Hoot Owl','preparer'),
(3, 'strategicartscollaborative@gmail.com', 'testsa', 'Strategic Arts','reviewer');

-- Insert a Template Name
INSERT INTO templates (template_id, template_name, user_id, updated_at) VALUES
(1, 'compliance testing', 1, '2020-08-11'),
(2, 'client compliance guide', 1, '2020-08-11');

INSERT INTO template_questions (template_name, template_question_id, question, yes_text, no_text, not_applicable_text,help_text,resource_url,
                                category, primary_driver)
VALUES
('compliance testing', 1, '1. Has the census been received?', 'Census received','Census missing. Plan is/will be placed on hold.','A census must be provided. Not applicable is not an appropriate response.','If the census is missing, e-mail the relationship manager immediately prepare the folders and pull any reporting such as trust statements and start the trust reconciliation. Once you have gotten as far as possible, place the plan on hold.','https://www.youtube.com','CENSUS',false),
('compliance testing', 2, '2. Has the questionnaire been received?', 'Questionnaire received.','no_text','not_applicable-text','help_text','https://www.youtube.com','category',false),
('compliance testing', 3, '3. Is the census formatted in a format that can be directly loaded into the system?', 'Census is in a format ready for load.','no_text','not_applicable-text','help_text','https://www.youtube.com','category',false),
('compliance testing', 4, '4. Has the census been loaded to the system?', 'Census loaded.','no_text','not_applicable-text','help_text','https://www.youtube.com','category',false),
('compliance testing', 5, '5. Has an Eligibility proof been prepared from the census that separates employees into the categories HCEs, NHCEs, Ineligibles(with explanation such as age,service), Excluded, Prior Year Terms?', 'Eligibility Proof employee classifications have been made.','no_text','not_applicable-text','help_text','https://www.youtube.com','category',false),
('compliance testing', 6, '6. Does the proof indicate the HCEs percentages, relationships and attribution for all employees with the same name as owner-employees, those earning over $120,000 in a prior year?', 'Owner percentages, relationships for those with the same last name as the owners and other relatives, and persons making over $120,000 in the last year have been marked in the file.','no_text','not_applicable-text','help_text','https://www.youtube.com','category',false),
('compliance testing', 7, '7. Does the proof indicate the estimated Actual Deferral Percentage and properly cap the deferrals and the compensation considered at the at the limit for the year tested?"', 'Preliminary ADP ACP Results have been calculated and compared to the reports generated by the system. Variances have been resolved.','no_text','not_applicable-text','help_text','https://www.youtube.com','category',false),
('compliance testing', 8, '8. Have you indicated whether the plan uses Prior Year Testing and confirmed that the system is correctly set-up for Prior Year Testing?', 'The Prior Year Testing numbers have been entered.','no_text','not_applicable-text','help_text','https://www.youtube.com','category',false),
('compliance testing', 9, '9. Have you confirmed the formula for any Match and ensured it is entered in the testing system? Enter NA if the plan either does not have a match source or will not be funding a match this year.', 'Match formula confirmed and entered and results checked.','no_text','not_applicable-text','help_text','https://www.youtube.com','category',false),
('compliance testing', 10, '10. Have you confirmed the formula for any Safe Harbor Match and ensured it is entered in the testing system?', 'Safe Harbor match formula confirmed and entered and results checked.','no_text','not_applicable-text','help_text','https://www.youtube.com','category',false),
('compliance testing', 11, '11. Have you verified the Match if the plan requires calculation and is on an annual basis according to the plan document/adoption agreement?', 'Match basis has been checked and whether a calculation is required was verified.','no_text','not_applicable-text','help_text','https://www.youtube.com','category',false),
('compliance testing', 12, '12. If the plan is a sole proprietorship or partnership and has Schedule C or Schedule K income that is not passing through as W-2 income, has the owner/all partners signed participation agreements?', 'All participation agreements for participating employers signed.','no_text','not_applicable-text','help_text','https://www.youtube.com','category',false),
('compliance testing', 13, '13. Has the income for sole proprietors/partners been entered correctly based on either Draft or final Schedule C or K-1 documents? Search for Entity Type in the plan document/adoption agreement to identify if the plan is a sole proprietorship/partnership not taxed as a corporation.', 'Schedule C or K income entered completely on file and draft or final schedules provided.','no_text','not_applicable-text','help_text','https://www.youtube.com','category',false),
('compliance testing', 14, '14. Did you load and generate the ADP and ACP Tests?', 'ADP ACP tests generated.','no_text','not_applicable-text','help_text','https://www.youtube.com','category',false),
('compliance testing', 15, '15. Do the ADP and ACP tests match your expectations on the proof or if not have you explained the differences and made the adjustments needed to tie out the system to the census?', 'ADP and ACP tests match expectations based on proof/prior testing review.','no_text','not_applicable-text','help_text','https://www.youtube.com','category',false),
('compliance testing', 16, '16. Has all the income for employees been accounted for?', 'All employee income accounted for.','no_text','not_applicable-text','help_text','https://www.youtube.com','category',false),
('compliance testing', 17, '17. Did the client provide excluded compensation for the Match calculation?', 'Excluded Compensation was provided for the match.','no_text','not_applicable-text','help_text','https://www.youtube.com','category',false),
('compliance testing', 18, '18. Have you checked for plan Match excesses if the plan Match is on an allocation or payroll period basis?', 'Match excess checked.','no_text','not_applicable-text','help_text','https://www.youtube.com','category',false),
('compliance testing', 19, '19. Have you prepared the Match Contribution file for either the contribution/calculation or excesses?', 'The match file has been prepared.','no_text','not_applicable-text','help_text','https://www.youtube.com','category',false),
('compliance testing', 20, '20. Did the client provide the formula and classes for the Profit Sharing or Nonelective calculation? Enter N if the client was undecided. Enter NA if no Profit Sharing source or contribution to be made.', 'The Profit Sharing/Nonelective formula was provided or is specified in the document.','no_text','not_applicable-text','help_text','https://www.youtube.com','category',false),
('compliance testing', 21, '21. Did the client provide excluded compensation for the Profit Sharing or Nonelective calculation?', 'Excluded compensation was provided.','no_text','not_applicable-text','help_text','https://www.youtube.com','category',false),
('compliance testing', 22, '22. If the plan is cross-tested, that is, every individual is in their own class and is making a Profit Sharing/Nonelective contribution have you confirmed the formula calculations?', 'Profit Sharing/Nonelective calculations have been confirmed.','no_text','not_applicable-text','help_text','https://www.youtube.com','category',false),
('compliance testing', 23, '23. Have you prepared the Profit Sharing/Nonelective Contribution file for either the contribution/calculation or excesses?', 'Profit Sharing/nonelective contribution file prepared.','no_text','not_applicable-text','help_text','https://www.youtube.com','category',false),
('compliance testing', 24, '24. Have you confirmed that HCEs by Attribution are identified in the file?', 'Owner family members and persons with same last name as owners have relationship to owners identified.','no_text','not_applicable-text','help_text','https://www.youtube.com','category',false),
('compliance testing', 25, '25. Did you load the participant source activity?', 'Participant contribution by source loaded.','no_text','not_applicable-text','help_text','https://www.youtube.com','category',false),
('compliance testing', 26, '26. Have you printed the Top Heavy Test for next testing year and the current allocation if the plan is not a 100% Union or 403(b) plan and one of the following situations apply: The plan is receiving (1) Deferrals only, (2) Deferrals and Match only or (3) Deferrals and a Safe Harbor contribution and is making Profit Sharing/Nonelective contributions?', 'Top Heavy Allocation & Test Printed.','no_text','not_applicable-text','help_text','https://www.youtube.com','category',false),
('compliance testing', 27, '27. Did you load vesting?', 'Vesting loaded.','no_text','not_applicable-text','help_text','https://www.youtube.com','category',false),
('compliance testing', 28, '28. Did you confirm census contributions against the trust and provide a true-up file for any variances?', 'Trust accounting complete.','no_text','not_applicable-text','help_text','https://www.youtube.com','category',false),
('compliance testing', 29, '29. Has the client responded to all questions?', 'Client has responded to all questions.','no_text','not_applicable-text','help_text','https://www.youtube.com','category',false),
('compliance testing', 30, '30. Have all the client responses been entered?', 'Client responses all entered.','no_text','not_applicable-text','help_text','https://www.youtube.com','category',false),
('compliance testing', 31, '31. Have you regenerated the reports and re-confirmed the numbers?', 'Reports reprinted and re-reconciled.','no_text','not_applicable-text','help_text','https://www.youtube.com','category',false),
('compliance testing', 32, '32. Did you print the Title Page?', 'Title page printed.','no_text','not_applicable-text','help_text','https://www.youtube.com','category',false),
('compliance testing', 33, '33. Did you print the Table of Contents?', 'Table of contents printed.','no_text','not_applicable-text','help_text','https://www.youtube.com','category',false),
('compliance testing', 34, '34. Did you print the Results Summary?', 'Results summary printed.','no_text','not_applicable-text','help_text','https://www.youtube.com','category',false),
('compliance testing', 35, '35. Did you print the ADP and ACP Nondiscrimination Test or ADP Nondiscrimination Test, as applies?', 'ADP/ACP report printed.','no_text','not_applicable-text','help_text','https://www.youtube.com','category',false),
('compliance testing', 36, '36. Did you print the Catch-Up Contributions Summary?', 'Catch-Up contribution report printed.','no_text','not_applicable-text','help_text','https://www.youtube.com','category',false),
('compliance testing', 37, '37. Did you print the Annual Additions Test?', 'Annual Additions report printed.','no_text','not_applicable-text','help_text','https://www.youtube.com','category',false),
('compliance testing', 38, '38. Did you print the General Test under 401(a)(4)?', 'General Test printed.','no_text','not_applicable-text','help_text','https://www.youtube.com','category',false),
('compliance testing', 39, '39. Did you print the Budget Report for Sole Proprietorships/Partnerships with Schedule C or K income?', 'Budget printed.','no_text','not_applicable-text','help_text','https://www.youtube.com','category',false),
('compliance testing', 40, '40. Did you print the 414(s) test if excluded compensation other than 125, reimbursements or date of participation compensation was used?', '414(s) printed.','no_text','not_applicable-text','help_text','https://www.youtube.com','category',false),
('compliance testing', 41, '41. Did you place a copy of the census in the working papers folder, all review files in the Review Folder and all Client Files including reports and contribution and refund files in the Client Folder?', 'Files saved to folders.','no_text','not_applicable-text','help_text','https://www.youtube.com','category',false),
('compliance testing', 42, '42. Did you enter the contributions for deferrals and roth for the three relevant periods as necessary if the plan is an Off-Calendar (fiscal year end) plan?', 'Off-calendar 402(g) numbers entered.','no_text','not_applicable-text','help_text','https://www.youtube.com','category',false),
('compliance testing', 43, '43. Did you update vesting to 100% if the plan terminated and has a signed termination agreement and did you adjust the testing compensation by the ratio of months in the plan year based on the year end date?', 'Plan Termination vesting updated.','no_text','not_applicable-text','help_text','https://www.youtube.com','category',false),
('compliance testing', 44, '44. For plans with Short Plan Years did you adjust the testing compensation, the deferral limits and any required hours for testing?"', 'Short Plan Year compensation, deferral limits and hours adjustments made.','no_text','not_applicable-text','help_text','https://www.youtube.com','category',false),
('compliance testing', 45, '45. Has the relevant tracking database been updated?', 'Tracking database updated.','no_text','not_applicable-text','help_text','https://www.youtube.com','category',false),
('compliance testing', 46, '46. If the plan had late deferrals, have you logged a request to prepare a submission in the relevant tracking database?', 'Late deferrals tracking record created.','no_text','not_applicable-text','help_text','https://www.youtube.com','category',false),
('compliance testing', 47, '47. Have you logged a request to begin preparation of the 5500, Summary Annual Report and 8955-SSA in the relevant tracking database?', 'Government Forms Tracking created.','no_text','not_applicable-text','help_text','https://www.youtube.com','category',false),
('client compliance guide', 48, 'Is your file organized with the same top row as the initial file downloaded?', 'Headers fine.','no_text','not_applicable-text','help_text','https://www.youtube.com','category',false),
('client compliance guide', 49, 'Apply a filter across the rows in the original template. When you filter social security numbers are there any blanks?', 'Social Security Numbers fine.','no_text','not_applicable-text','help_text','https://www.youtube.com','category',false),
('client compliance guide', 50, 'When you filter dates of birth are there any blanks?', 'Dates of Birth Fine.','no_text','not_applicable-text','help_text','https://www.youtube.com','category',false),
('client compliance guide', 51, 'When you filter dates of birth are there any for persons under 18', 'Dates of birth for young employees are correct.','no_text','not_applicable-text','help_text','https://www.youtube.com','category',false),
('client compliance guide', 52, 'When you filter dates of birth are there any for persons over 80 who should not be', 'Retiree dates of hire fine.','no_text','not_applicable-text','help_text','https://www.youtube.com','category',false),
('client compliance guide', 53, 'When you filter dates of hire are there any blanks', 'Dates of Hire fine.','no_text','not_applicable-text','help_text','https://www.youtube.com','category',false),
('client compliance guide', 54, 'Are there any blank dates of rehire for persons who have a termination date prior to this year and received compensation?', 'Dates of Rehire fine.','no_text','not_applicable-text','help_text','https://www.youtube.com','category',false),
('client compliance guide', 55, 'Are there any termination dates for people before rehire dates?', 'Dates of rehire after termination fine.','no_text','not_applicable-text','help_text','https://www.youtube.com','category',false),
('client compliance guide', 56, 'When you apply a filter do you have percentages in the ownership column that add up to 100% or is not have you explained on tab 2?', 'Owners identified.','no_text','not_applicable-text','help_text','https://www.youtube.com','category',false),
('client compliance guide', 57,'Have you placed a Y in the officer column for each officer or explained on tab 2 that there are no officers', 'Officers have been marked in the file.','no_text','not_applicable-text','help_text','https://www.youtube.com','category',false),
('client compliance guide', 58,'Have you indicated the relationship of all family members for anyone who has a relationship to the owner(s)?', 'Family attribution has been noted in the file, including for persons with the same last names as the owners.','no_text','not_applicable-text','help_text','https://www.youtube.com','category',false),
('client compliance guide', 59,'Have you entered a formula for the Match or entered no match on tab 2?', 'Match contributions clarified - either none or for yes, formula and principal class numbers and budget provided.','no_text','not_applicable-text','help_text','https://www.youtube.com','category',false),
('client compliance guide', 60,'Have you entered a formula for Profit Sharing including the class of each person based on how much Profit Sharing they should receive if eligible in the Principal column?', 'Profit sharing/nonelective contributions clarified - either none or for yes, formula and principal class numbers and budget provided.','no_text','not_applicable-text','help_text','https://www.youtube.com','category',false),
('client compliance guide', 61,'Excluded Compensatzion must be excluded in the plan document to be disregarded in calculating the Match/Profit Sharing. Have you confirmed that you did not enter the same amount as the compensation for participants not yet eligible to participate in the plan?', 'Excluded compensation provided.','no_text','not_applicable-text','help_text','https://www.youtube.com','category',false),
('client compliance guide', 62,'Excluded Employees must be excluded in the plan document to be disregarded in testing. Have you marked all these employees with a Y?', 'Excluded employees marked - fine.','no_text','not_applicable-text','help_text','https://www.youtube.com','category',false),
('client compliance guide', 63,'If your plan transferred to us in the middle of the plan year, did you provide the prior testing results?', 'Prior testing results provided.','no_text','not_applicable-text','help_text','https://www.youtube.com','category',false),
('client compliance guide', 64,'If your plan transferred to us in the middle of the plan year, did you provide the prior custodians statement of contributions by participant by money type(source)?', 'Prior contribution data was provided.','no_text','not_applicable-text','help_text','https://www.youtube.com','category',false),
('client compliance guide', 65,'If your entity is a Sole Proprietorship or Partnership have you entered Schedule C or Schedule K income on the spreadsheet and provided draft or actual Schedules?', 'Schedule C or K income entered comepletely on file and draft or final schedules provided.','no_text','not_applicable-text','help_text','https://www.youtube.com','category',false),
('client compliance guide', 66,'Have you identified any Schedule K recipients who are actually receiving income as W-2 income?', 'Schedule K participants receiving such income as W-2 income identified.','no_text','not_applicable-text','help_text','https://www.youtube.com','category',false),
('client compliance guide', 67,'Are all participation agreements in place for all participating employers, especially if the sponsor is a partnership or sole proprietorship?', 'Participation agreements in place for all participating employers.','no_text','not_applicable-text','help_text','https://www.youtube.com','category',false),
('client compliance guide', 68,'Has all the income for employees been accounted for or have you explained who has not on tab 2?', 'All income provided. Matches W-3.','no_text','not_applicable-text','help_text','https://www.youtube.com','category',false);




